# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=200)),
                ('slot_status', models.CharField(default='free', max_length=100)),
            ],
        ),
    ]
