# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parking', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
